### ISSUE TITLE
Terms Of Use

### ISSUE THREAD

**Issue by fulllinuxpi** [darioragusa/JWLibrary-MediaInserter#1]
Have you ever had problems with the term of use below?

YOUR USE OF JW LIBRARY®

1. What proper use? JW Library has been designed to download, organize, and display Watch Tower's electronic publications for your personal, non-commercial use only. Hence, you may not post any portion of the Watch Tower’s electronic publications on the Internet or on any other electronic network or use the publications commercially or in exchange for money — **even if no profit is involved. Modification of the JW Library app is not permitted.**

I await reply!

**Comment by darioragusa** [comment]
No, never. Despite the name, I'm not modifying the app, I'm modifying the publications.

**Comment by fulllinuxpi** [comment]
Just one more thing. Maybe put the restore function from the deprecated version!

Hug!

**Comment by darioragusa** [comment]
Yeah, they have already asked me 😅. It will arrive in a future update.
