### ISSUE TITLE
Detalle visual version 1.1.0

### ISSUE THREAD

**Issue by rperez10** [darioragusa/JWLibrary-MediaInserter#12]
Hola, estoy muy agradecido por su trabajo. Solo en la version 1.1.0 en la ventana no se visualizan los controles nuevos para ver todas las publicaciones y exportar el jwpub. Se que existe porque si doy tecla TAB y presiono enter veo que hay otras opciones abajo.
Quiza solo es el entorno visual que no se agrando a la hora de empaquetar. Mando captura de pantalla.

![image](https://user-images.githubusercontent.com/110516302/182524493-c6df5f4a-8f7c-4372-b739-775056a7067f.png)
                 Aqui se ve que no entra completo el insertar
Y no se ven las opciones de abajo

**Comment by darioragusa** [comment]
Hi, really strange, I've tried on two different computer and it seems to work
![image](https://user-images.githubusercontent.com/46404000/182544566-3caab3cb-8f41-4c76-b852-c2519a1b087d.png)
Can you try to uninstall and install it again?

**Comment by rperez10** [comment]
Hola, si ya intente desinstar, limpiar y reiniciar compuadora, instalar nuevamente y sigue igual.

No se si aparte hay algun lugar donde se guarde informacion de la instalacion en la pc que quede sin borrar al eliminar

**Comment by rperez10** [comment]
no se si tenga que ver que la resolucion maxima de mi lap sea de 1366x768 quiza sea eso, y ya no puedo aumentarla

**Comment by darioragusa** [comment]
Yes, the form is slightly bigger, 787x880

**Comment by rperez10** [comment]
Quiza pudieras hacer algo para que se abra de manera apropiada. Porque si le doy la opción de girar pantalla a vertical si lo abre bien, pero en horizontal no. Y pues todos usamos el computador con la pantalla en horizontal. 
No se si hay forma de que se arregle, o que se ajuste todo a el tamaño anterior

**Comment by darioragusa** [comment]
I'll find a way to reduce the window size

**Comment by darioragusa** [comment]
Hi, I made a new release: you should be able to resize the window vertically, let me know if you still have problems

**Comment by rperez10** [comment]
Hola desde que se abre ell programa ya aparece bien con todas las opciones, tambien la opcion de cambiar tamaño de ventana es bueno. Gracias.

**Comment by darioragusa** [comment]
You're welcome!
