### ISSUE TITLE
I get an error in the code

### ISSUE THREAD

**Issue by livrasand** [darioragusa/JWLibrary-MediaInserter#14]
Hey bro! How are you? I am adding your new version to my Attendant Zoom application, and I see this small error that I cannot solve, I have installed the dependencies, will I need any? I attach the following screenshots.

![Captura de pantalla (172)](https://user-images.githubusercontent.com/104039397/198885150-c7d21a9e-6fce-4e7d-b60b-c98929bf7b0e.png)
![Captura de pantalla (173)](https://user-images.githubusercontent.com/104039397/198885164-5f50e341-c902-4fd5-8e8a-12548f5b3a59.png)

**Comment by darioragusa** [comment]
Hi, I'm fine thanks. I don't know, what's the error? [As you can see](https://github.com/darioragusa/JWLibrary-MediaInserter/commit/3b7d0e047f1b63e9c0954f4fe126f4fc7e6510b2) I've not modified that file. By the way the package I used is this one
![image](https://user-images.githubusercontent.com/46404000/198885569-2bf7b40d-eeb5-4a39-a1ec-c2742af2b640.png)

**Comment by livrasand** [comment]
Ok thanks, I'll see how to fix it

**Comment by livrasand** [comment]
Thank you very much friend and brother. Now resolved, I was using the wrong NuGets.
