### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by saulotarsobc** [darioragusa/JWLibrary-MediaInserter#15]
Como posso falar com voce? tem whatsapp?

How can I talk to you? do you have Whatsapp?

**Comment by darioragusa** [comment]
Hi, yes I have WhatsApp but if it's not a super secret question you can ask me here. Also because I don't speak Portuguese and my English isn't that good

**Comment by saulotarsobc** [comment]
ah yes. Thanks. My English is basic lol. wanted your help creating '.jwpub' files. Can you help? :)

**Comment by darioragusa** [comment]
I've never created a .jwpub file, so I may not be as helpful as you think. The best I can do is link you to [this comment](https://github.com/darioragusa/JW-Library-macOS/issues/1#issuecomment-1079989526) as starting point. In that thred you can also find how words are indexed, the rest would be new to me as well.

**Comment by saulotarsobc** [comment]
thank you very much. I think this comment will help. 😊

**Comment by saulotarsobc** [comment]
thank you very much. I think this comment will help. 😊

**Comment by gokusander** [comment]
> thank you very much. I think this comment will help. 😊

you create a .jwpub? I created it but it's not opening, according to "livrasand" it said it's the paragraph table. But it still doesn't work and I waiting for him a few days ago. But nothing...

-------------------------------------------------------------

Conseguiu criar um .jwpub? Eu criei mas não está abrindo, segundo o "livrasand" disse que é a tabela de parágrafos. Mas mesmo assim não funciona e ele sumiu tem uns dias.

**Comment by saulotarsobc** [comment]
I couldn't learn. Livrado doesn't have time to teach better.

**Comment by gokusander** [comment]
> I couldn't learn. Livrado doesn't have time to teach better.

Você entende de banco de dados?  Estou apanhando nisso infelizmente, tem coisas tipo sqlite1, word, search, paragraph que não sei como preencher. O resto consigo e posso repassar publicamente, acho bom cada um poder criar o seu.

Os blobs (que ele diz para solicitar para ele) aqui o ghost postou como gerar, então ficou fácil gerar seu próprio blob sem depender do livrado. Se quiser podemos tentar, mas não sou programador, meu trabalho é na área da saúde. Apenas querendo criar algo para estudar a bíblia.

Você conseguiu ir até que parte?

------------

Do you understand .db? Unfortunately, I'm dont understand. There are things like sqlite1, word, search, paragraph that I don't know what I put. I can do the rest and share it, for me it's ok. I think it's good for everyone to be able to create their own.

Ghost posted how to generate the blobs (Livrado says you should request for him), so it's easy to generate your own blob without him. If you want, we can try, but I'm not a programmer. I work in the hospital lol. I just want to create something to study the Bible.

What you can create about .jwpub?
