### ISSUE TITLE
Problem when adding a video or videos

### ISSUE THREAD

**Issue by oscarias68** [darioragusa/JWLibrary-MediaInserter#17]
Hello, friend. When i try to add videos i have this message. Thank you

![2023-03-30 21_53_21-JWLibrary-MediaInserter](https://user-images.githubusercontent.com/70296432/229011150-3703d516-556c-4af0-9d52-ed0e61fc28dc.jpg)

**Comment by rperez10** [comment]
Hola, tienes instalada la version mas reciente que es la 1.2
Yo comente hace unos meses de ese problema y con esa actualizacion se soluciona

**Comment by darioragusa** [comment]
Hi, can you send the details? Was the video open in another program?

**Comment by rperez10** [comment]
Hola, me imagino que debe tener instalada una version anterior del programa. A mi me dio el mismo problema, lo comente en el Issue #13 y con la version 1.2.0 se soluciono. Quiza deba instalar la version mas reciente.
Esperemos sus comentarios

**Comment by oscarias68** [comment]
Solucionado. Desinstalé y volví a instalar. Gracias

**Comment by darioragusa** [comment]
Ok
