### ISSUE TITLE
Missing frameworks for .NET

### ISSUE THREAD

**Issue by joshdejuan** [darioragusa/JWLibrary-MediaInserter#5]
Hi. When I run the program it shows this message even when I have downloaded and installed the [frameworks for .NET](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime?cid=getdotnetcore).

![photo_2022-05-28_12-04-48](https://user-images.githubusercontent.com/64188000/170820684-31a86a35-2c4b-4c43-831d-a7f9cac4de28.jpg)

**Comment by darioragusa** [comment]
Hi, I have no idea. Have you tried to restart the computer? Uninstall and reinstall the application?

**Comment by darioragusa** [comment]
Hi, were you able to solve the issue?

**Comment by joshdejuan** [comment]
Yes, it was my fault. Instead of downloading **.NET for desktop apps** I was downloading for **console apps**. Now it is working perfectly.
