### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by fulllinuxpi** [darioragusa/JWLibrary-MediaInserter#6]
Hello friend, follow translation for **Pt_br**

[https://drive.google.com/file/d/14ggE1-XeyzRB225-f_3r-CTm3D-L0sst/view?usp=sharing](url)

**Comment by darioragusa** [comment]
Hi, many thanks for the contribution. If you make a pull request you will be listed as contributor, otherwise I'll add the file myself. Just a thing: the file should be named `Resources.pt-BR.resx`

**Comment by fulllinuxpi** [comment]
Good job!!!
