### ISSUE TITLE
Could this work on Electron?

### ISSUE THREAD

**Issue by livrasand** [darioragusa/JWLibrary-MediaInserter#7]
Do you know how I can make this work in HTML and JavaScript with Electron? My Attendant Zoom app is currently working with your code snippet. But I would like to port my app to Electron, and see the possibility of using this GREAT feature.

**Comment by darioragusa** [comment]
Hi, from what I'm reading on internet Electron uses Node.js as backend so with a sqlite library you should be able to replicate the code

**Comment by darioragusa** [comment]
I don't know, I've never used that. Maybe something like:
[https://stackoverflow.com/questions/32504307/how-to-use-sqlite3-module-with-electron](https://stackoverflow.com/questions/32504307/how-to-use-sqlite3-module-with-electron)
[https://www.youtube.com/watch?v=nMvjcBTFlPA&ab_channel=coderJeet](https://www.youtube.com/watch?v=nMvjcBTFlPA&ab_channel=coderJeet)

**Comment by livrasand** [comment]
I already solved it, I will use Blazor for the conversion. Then I'll connect it to Electron. You will be able to see the published application later in my repository. Thanks for the input!
