### ISSUE TITLE
Ability to inject Media in any jwpub?

### ISSUE THREAD

**Issue by lukefarr** [darioragusa/JWLibrary-MediaInserter#9]
Hi. Can your app inject media into any jwpub? 
My use case would be the following: I have a collection of various charts/images that have been published that help explain complex subjects. Eg the picture from the WT this week. 
Having a publication on all my devices that contains all of these in one place would be amazing.

**Comment by darioragusa** [comment]
Hi, to answer the first question: teorically yes, if you see [here ](https://github.com/darioragusa/JWLibrary-MediaInserter/blob/7231e3a65aa0be3e959ac658d26b39165d4d4b53/JWLibrary-MediaInserter/Modules/FindPubs.vb#L51) the list is filtered. So for example, you insert an image in a publication and then export the .jwpub file to use it elsewhere. It should be doable but only for images as the videos are stored separately.

**Comment by darioragusa** [comment]
Yes, I will make a new release with the ability to turn the filter on/off.
.jwpub files are just zip that contains another zip and the content of this file is stored inside a folder in `C:\Users\39392\AppData\Local\Packages\WatchtowerBibleandTractSo.45909CDBADF3C_5rz59y55nfz3e\LocalState\Publications\` (IDK if "45909CDBADF3C_5rz59y55nfz3e" is different in different machines). I think that zipping it back should works
